-- Процедура заливки пользователей WMS для ИНКО
if db_name() <> 'WMS' return

set nocount on

-- _Users
-- Бригада №1
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Юрлов Е.М.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Николаев Ю.Г.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Цветков М.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Дарий В.Г.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Семенов В.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Чаликов М.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Трушин С.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Антипов В.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Гущин В.М.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Рябов И.Ю.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Кириллов А.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Балаев М.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Кузнецов Е.Ф.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Чекашов В.Н.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Носов В.В.', '', 0, 1)

-- Бригада №2
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Щербак С.И.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Почеховский С.М.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Почеховский И.М.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Уколов А.Ф.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Пономарев Ю.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Иванов А.И.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Орлов В.И.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Коженков И.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Троцько А.Н.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Пеньков А.Ю.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Агафонов А.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Миллер Н.Н.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Вилков К.К.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Валитов А.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Сидоров А.Ю.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Терновой Н.В.', '', 0, 1)

-- Бригада №3
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Дугин Д.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Таковицкий В.Е.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Востриков А.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Чепурнов А.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Устинов Д.П.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Ширяев Т.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Сорокин М.И.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Кондрашов М.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Глазунов А.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Калинкин В.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Гуськов С.С.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Чуркин Ю.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Платонов Д.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Коршунов А.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Бегиджонов С.А.', '', 0, 1)

-- Бригада №4
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Суслянок Ю.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Тупиков Ю.С.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Грунт А.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Харламов М.Н.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Сиволапов Е.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Пичугин А.Н.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Тропенков К.К.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Сапрыгин Д.Н.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Новиков С.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Титов В.И.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Буланов В.А.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Пискарёв Д.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Стариков А.С.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Сальников И.Н.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Вахнин Д.В.', '', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Шиндяков А.Н.', '', 0, 1)

-- Операторы ООД
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Орлова С.А.', 'jh94', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Акашина Е.А.', 'trakash', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Гапанькова И.В.', 'uf93', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Ахметова Л.Н.', 'fp04', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Королева А.А.', 'rokaa', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Денисенко Л.М.', 'esine', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Насакин М.В.', 'trnas', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Кудрицкая С.А.', 'trkudr', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Четверикова Л.В.', 'xt62', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Ераскина О.И.', 'askin', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Корогодова Е.Б.', 'trkoro', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Максименко Л.И.', 'trmaks', 0, 1)

-- Администрация склада
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Левитин Д.В.', 'dima', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Юрлов М.Н.', 'sklad', 0, 1)
insert into _Users (Name, Password, IsAdmin, Actual) 
	values ('Макаров В.Л.', 'kt62', 0, 1)

declare @nID int
declare _U cursor for 
	select ID from _Users 
	where len(ltrim(Password)) = 0 
	order by Name
open _U

fetch next from _U into @nID
while @@fetch_status = 0 begin
	update _Users set Password = right(cast(newid() as varchar(max)), 12) 
		where ID = @nID
	fetch next from _U into @nID
end

close _U
deallocate _U

