truncate table _Menus
set identity_insert _Menus on
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (1, 0, 'Внешние операции', 1, 1, '', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (2, 0, 'Склад', 2, 1, '', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (3, 0, 'Перемещения', 3, 1, '', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (4, 0, 'Отчеты', 4, 1, '', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (5, 0, 'Справочники', 5, 1, '', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (6, 0, 'Права доступа', 6, 1, '', '', 1, 1)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (7, 1, 'Приходы', 1, 1, 'frmInputs', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (8, 1, 'Расходы', 2, 1, 'frmOutputs', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (9, 1, 'Акты', 2, 1, 'frmOutputs', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (10, 2, 'Ячейки', 1, 1, 'frmCells', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (11, 2, 'Остатки', 2, 1, 'frmOddments', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (12, 3, 'Операции перемещения контейнеров', 1, 1, 'frmTrafficsFrames', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (13, 3, 'Операции перемещения коробок/штук', 2, 1, 'frmTrafficsGoods', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (14, 3, 'Контейнеры и их текущее расположение', 3, 1, 'frmFrames', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (15, 4, 'Информация о штрих-коде', 1, 1, 'frmReportsBarCode', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (16, 4, 'Операции с ячейками/контейнерами', 2, 1, 'frmReportCellsFramesHistory', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (17, 4, 'Транспортировки и перемещения', 3, 1, 'frmReportTraffics', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (18, 4, 'Остатки и операции за период', 4, 1, 'frmReportOddmentsBalance', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (19, 4, 'Товары/упаковки', 5, 1, 'frmSelectOnePacking', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (20, 5, 'Таблицы', 1, 1, 'frmSysLook', '', 1, 1)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (21, 5, 'Пользователи', 2, 1, 'frmUsers', '', 1, 0)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (22, 6, 'Права на главное меню', 2, 1, 'frmAccessMenu', '', 1, 1)
insert into _Menus (ID, ParentID, ItemText, ByOrder, Actual, CmdName, CmdParam, IsForm, IsAccessOn) 
	values (23, 6, 'Права на элементы форм', 2, 1, 'frmAccessControls', '', 1, 1)
set identity_insert _Menus off
